accounts/urls.py
from django.urls import path
from django.views.generic import RedirectView
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView)
from .views import sign_up, sign_up_with_account_password, sign_up_with_chief_email, profile_change, set_role
from .forms import EmailValidationOnForgotPassword


# we use many built-in auth-related views from django.contrib.auth.urls
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    # we override this form class of this view
    path('password-reset/', PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

# some custom views
urlpatterns += [
    path('sign-up/', sign_up, name='sign_up'),
    path('sign-up/with-account-password/', sign_up_with_account_password, name='sign_up_with_account_password'), # not shown directly on web interface
    path('sign-up/with-chief-email/', sign_up_with_chief_email, name='sign_up_with_chief_email'),
    path('profile/', profile_change, name='profile_change'),
    path('set-role/<str:role>/', set_role, name='set_role')
]

mail_job/urls.py
from django.urls import path
from .views import change_list, add, change, delete, mail_test


app_name = 'mail_job'

urlpatterns = [
    path('', change_list, name='change_list'),
    path('add/', add, name='add'),
    path('<int:seq>/change/', change, name='change'),
    path('<int:seq>/delete/', delete, name='delete'),
    path('<int:seq>/mail-test/', mail_test, name='mail_test'),
]

mssqlj3y/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('mail-job/', include('mail_job.urls')),
    path('', RedirectView.as_view(url='/mail-job/'), name='index'),
]

mail_job/models.py
from django.db import models

# Create your models here.

mail_job/views.py
from django.shortcuts import render
from django.utils import timezone
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.translation import gettext as _
from django.contrib import messages
import pandas
from .mssql_sp import (
    exec_query, sp_show_mail_job, sp_show_mail_job_1,
    sp_insert_mail_job, sp_update_mail_job, sp_do_mail_job_onetime,
    sp_insert_mail_job_1, sp_update_mail_job_1, sp_show_mail_job_2,
    sp_do_mail_job_onetime_1
)
from .forms import MailJobAddForm, MailJobUpdateForm
from accounts.views import get_role


def change_list(request):
    """
    A view of Mail Job change list.
    """
    if not request.user.is_authenticated:
        return redirect(reverse('login'))
    context = {
        'tips': [],
        'df': None
    }
    show_history = request.GET.get('show_history', '') == 'true'
    try:
        response_show = sp_show_mail_job_2()
        df = pandas.DataFrame(tuple(row) for row in response_show)
        df.columns = [
            'result',  # 查詢結果
            'seq',  # 項次
            'mode_send',  # 寄送模式
            'department',  # 部門
            'event_class',  # 事件類型
            'event',  # 事件
            'note_date',  # 通知起始日
            'period',  # 週期
            'weekend_flag',  # 假日除外
            'subject',  # 郵件主旨
            'body',  # 郵件內容
            'recipient_add',  # 額外內容
            'recipient',  # 收件人
            'start_date',  # 建立時間
            'stop_date',  # 規則終止日
            'create_by',  # 建立者
            'update_by',  # 修改者
            'update_date',  # 修改日期
            'mail_count',  # 寄件次數
        ]
        departments = [get_role(request)]
        # Filter of department.
        df = df[df['department'].isin(departments)]
        # Filter of show_history.
        if not show_history:
            df = df[df['stop_date'].isin(['']) | (df['stop_date'] > str(timezone.localtime(timezone.now()).date()))]
        df.fillna('', inplace=True)
        df = df.sort_values(by=['start_date'], ascending=False)
        for index, row in df.iterrows():
            # mode_send readable choices
            choices_mode_send = {
                0: _('General'),
                1: _('Special'),
            }
            df.loc[index, 'mode_send_readable'] = choices_mode_send.get(row['mode_send'], 'Unknown')
            # period, weekend_flag() readable choices
            if row['period'] == '每日' and row['weekend_flag'] == 'T':
                df.loc[index, 'period_readable'] = _('Each weekday')
            else:
                choices_period = {
                    '單次': _('Once'),
                    '每日': _('Daily'),
                    '平日': _('Each weekday'),
                    '每週一': _('Each Monday'),
                    '每週二': _('Each Tuesday'),
                    '每週三': _('Each Wednesday '),
                    '每週四': _('Each Thursday '),
                    '每週五': _('Each Friday '),
                    '每週六': _('Each Saturday '),
                    '每週日': _('Each Sunday'),
                    '每月1號': _('1st of every month'),
                    '每月2號': _('2nd of every month'),
                    '每月3號': _('3rd of every month'),
                    '每月4號': _('4th of every month'),
                    '每月5號': _('5th of every month'),
                    '每月6號': _('6th of every month'),
                    '每月7號': _('7th of every month'),
                    '每月8號': _('8th of every month'),
                    '每月9號': _('9th of every month'),
                    '每月10號': _('10th of every month'),
                    '每月11號': _('11th of every month'),
                    '每月12號': _('12th of every month'),
                    '每月13號': _('13th of every month'),
                    '每月14號': _('14th of every month'),
                    '每月15號': _('15th of every month'),
                    '每月16號': _('16th of every month'),
                    '每月17號': _('17th of every month'),
                    '每月18號': _('18th of every month'),
                    '每月19號': _('19th of every month'),
                    '每月20號': _('20th of every month'),
                    '每月21號': _('21th of every month'),
                    '每月22號': _('22th of every month'),
                    '每月23號': _('23th of every month'),
                    '每月24號': _('24th of every month'),
                    '每月25號': _('25th of every month'),
                    '每月26號': _('26th of every month'),
                    '每月27號': _('27th of every month'),
                    '每月28號': _('28th of every month'),
                    '每月29號': _('29th of every month'),
                    '每月30號': _('30th of every month'),
                    '每月31號': _('31th of every month'),
                }
                df.loc[index, 'period_readable'] = choices_period.get(row['period'], _('Unknown'))
            # Cut the body longer than 50.
            if len(row['body']) > 50:
                df.loc[index, 'body'] = row['body'][:50] + '...'
            # Cut the recipient longer than 50.
            if len(row['recipient']) > 50:
                df.loc[index, 'recipient'] = row['recipient'][:50] + '...'
        context['df'] = df
    except Exception as e:
        print(e)
        context['tips'] += [_('Unknown error. The data cannot be returned.')]
    return render(request, 'mail_job/change_list.html', context)


def add(request):
    """
    A view of adding Mail Job.
    """
    if not request.user.is_authenticated:
        return redirect(reverse('login'))
    context = {
        'tips': [],
        'form': None,
    }
    if request.method != 'POST':
        form = MailJobAddForm()
        context['tips'] += [_('Fill in the following form to create a new mail job.')]
        context['form'] = form
        return render(request, 'mail_job/add.html', context)
    elif request.method == 'POST':
        form = MailJobAddForm(request.POST)
        context['form'] = form
        if form.is_valid():
            department = get_role(request)
            event_class = form.cleaned_data['event_class']
            event = form.cleaned_data['event']
            note_date = form.cleaned_data['note_date']
            period = form.cleaned_data['period']
            subject = form.cleaned_data['subject']
            body = form.cleaned_data['body']
            recipient = form.cleaned_data['recipient']
            if request.user.is_authenticated:
                created_by = request.user
            else:
                created_by = request.META.get('REMOTE_ADDR')
            if period == '平日':
                period = '每日'
                weekend_flag = 'T'
            else:
                weekend_flag = 'F'
        try:
            response_insert = sp_insert_mail_job(
                department=department,
                event_class=event_class,
                event=event,
                note_date=note_date,
                period=period,
                weekend_flag=weekend_flag,
                subject=subject,
                body=body,
                recipient=recipient,
                created_by=created_by,
            )
            if response_insert[0][0] == '新增成功':
                messages.add_message(request, messages.SUCCESS, _('Added successfully.'))
                return redirect(reverse('mail_job:change_list'))
            elif response_insert[0][0] == '新增失敗，資料重覆，請確認':
                messages.add_message(request, messages.ERROR, _(
                    'Failed to add. The data is duplicate with the existing.'))
            else:
                messages.add_message(request, messages.ERROR, _(
                    'Unknown error. The format of the return value is not correct.'))
        except Exception as e:
            print(e)
            context['tips'] += [_('Unknown error. The format of the return value is not correct.')]
        return render(request, 'mail_job/add.html', context)


def change(request, seq):
    """
    A view of changing Mail Job.
    """
    if not request.user.is_authenticated:
        return redirect(reverse('login'))
    context = {
        'tips': [],
        'seq': seq,
        'form': None,
    }
    if request.method == 'POST':
        form = MailJobUpdateForm(request.POST)
        context['form'] = form
        if form.is_valid():
            department = get_role(request)
            event_class = form.cleaned_data['event_class']
            event = form.cleaned_data['event']
            note_date = form.cleaned_data['note_date']
            stop_date = form.cleaned_data['stop_date']
            period = form.cleaned_data['period']
            subject = form.cleaned_data['subject']
            body = form.cleaned_data['body']
            recipient = form.cleaned_data['recipient']
            updated_by = request.user
            if period == '平日':
                period = '每日'
                weekend_flag = 'T'
            else:
                weekend_flag = 'F'
        try:
            response_update = sp_update_mail_job_1(
                seq=seq,
                department=department,
                event_class=event_class,
                event=event,
                note_date=note_date,
                period=period,
                weekend_flag=weekend_flag,
                subject=subject,
                body=body,
                recipient=recipient,
                stop_date=stop_date,
                updated_by=updated_by,
                mail_count='',
                mode_send='',
                recipient_add='',
            )
            if response_update[0][0] == '修改成功':
                messages.add_message(request, messages.SUCCESS, _('Changed successfully.'))
        except Exception as e:
            print(e)
            messages.add_message(request, messages.ERROR, _(
                'Unknown error. The format of the return value is not correct.'))
        return redirect(reverse('mail_job:change_list'))
    else:
        try:
            response_show = sp_show_mail_job(seq=seq)

mail_job/templates/mail_job/add.html
{% extends 'mail_job/base.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block extracss %}
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-auto" style="padding: 1.5rem;">
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-auto border border-j3y-theme-1 rounded bg-j3y-theme-1" style="padding: 1.5rem;">
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-row">
                    <div class="form-group col">
                        {{ field.label_tag }}
                        {% render_field field class+='form-control' %}
                        {% if field.errors %}
                        <p>{{ field.errors }}</p>
                        {% endif %}
                        {% if field.help_text %}
                        <small class="d-block text-muted">{{ field.help_text }}</small>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
                <div class="form-row">
                    <div class="form-group col">
                        {{ form.non_field_errors }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col">
                        <button type="submit" class="btn btn-primary btn-block">{% trans 'Add' %}</button>
                    </div>
                    <div class="form-group col">
                        <a href="{% url 'mail_job:change_list' %}"
                            class="btn btn-secondary btn-block">{% trans 'Get back' %}</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-auto" style="padding: 1.5rem;">
        </div>
    </div>
</div>
{% endblock %}

mail_job/templates/mail_job/base.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

mail_job/templates/mail_job/change.html
{% extends 'mail_job/base.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block extracss %}
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-auto" style="padding: 1.5rem;">
        </div>
    </div>
    {% if form %}
    <div class="row justify-content-center">
        <div class="col-auto border-j3y-theme-1 bg-j3y-theme-1" style="padding: 1.5rem;">
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-row">
                    <div class="form-group col">
                        {{ field.label_tag }}
                        {% render_field field class+='form-control' %}
                        {% if field.errors %}
                        <p>{{ field.errors }}</p>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
                {{ form.non_field_errors }}
                <div class="form-row">
                    <div class="form-group col">
                        <button type="submit" class="btn btn-primary btn-block">{% trans 'Change' %}</button>
                    </div>
                    <div class="form-group col">
                        <a href="{% url 'mail_job:change_list' %}"
                            class="btn btn-secondary btn-block">{% trans 'Get back' %}</a>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col">
                        <a href="{% url 'mail_job:mail_test' seq=seq %}"
                            class="btn btn-success btn-block">{% trans 'Mail Test' %}</a>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col">
                        <a href="{% url 'mail_job:delete' seq=seq %}"
                            class="btn btn-danger btn-block">{% trans 'Delete' %}</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% endif %}
    <div class="row justify-content-center">
        <div class="col-auto" style="padding: 1.5rem;">
        </div>
    </div>
</div>
{% endblock %}

mail_job/templates/mail_job/change_list.html
{% extends 'mail_job/base.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block extracss %}
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row" style="height: 4rem"></div>
    <div class="row justify-content-center">
        <div class="col-auto">     
            <div class="text-center">
                {% include 'brand.html' %}
                <h1>{% trans 'Reminder' %}</h1>
                <p class="text-secondary">{% trans 'For those you may miss.' %}</p>
            </div>
        </div>
    </div>
    <div class="row" style="height: 4rem"></div>
    <div class="row justify-content-center">
        <div class="col-auto">
            <div class="row my-0 mx-1">
                <div class="py-2 px-1 ml-auto">
                    <a class="btn btn-dark btn-block" style="width: 8rem; border-radius: .5rem" href="{% url 'mail_job:add' %}">{% trans 'Add' %}{% trans '+' %}</a>
                </div>
            </div>
            <div class="row my-0 mx-1">
                <div class="py-2 px-1 mr-auto">
                    <input type="text" class="form-control" id="filter-mail-job"
                        placeholder="{% trans 'Search..' %}">
                </div>
                <div class="py-2 px-1">
                    <select class="form-control" id="show-all-controller-mail-job">
                        <option value="personal">{% trans 'Personal' %}</option>
                        <option value="all">{% trans 'All' %}</option>
                    </select>
                </div>
                <div class="py-2 px-1">
                    <select class="form-control" id="field-controller-mail-job">
                        <option value="basic_field">{% trans 'Basic fields' %}</option>
                        <option value="all_field">{% trans 'All fields' %}</option>
                    </select>
                </div>
            </div>
            <table class="table table-bordered border-light table-hover table-responsive mail-job" id="table-mail-job">
                <thead>
                    <tr>
                        <th>{% trans 'Action' %}</th>
                        <th class="advanced-field">{% trans 'Dep.' %}</th>
                        <th>{% trans 'Event type' %}</th>
                        <th>{% trans 'Event' %}</th>
                        <th>{% trans 'Mode' %}</th>
                        <th>{% trans 'Start date' %}</th>
                        <th class="advanced-field">{% trans 'Stop date' %}</th>
                        <th>{% trans 'Period' %}</th>
                        <th>{% trans 'Mail subject' %}</th>
                        <th>{% trans 'Mail content' %}</th>
                        <th>{% trans 'Extra content' %}</th>
                        <th>{% trans 'Recipients' %}</th>
                        <th>{% trans 'Created by' %}</th>
                        <th>{% trans 'Created date' %}</th>
                        <th class="advanced-field">{% trans 'Updated by' %}</th>
                        <th class="advanced-field">{% trans 'Updated date' %}</th>
                        <th class="advanced-field">{% trans 'Executed times' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for index, row in df.iterrows %}
                    <tr>
                        <td id='td-action-mail-job'>
                            <div class="dropdown show">
                                <button class="btn btn-light bg-light dropdown-toggle" href="#" role="button"
                                    id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    {% trans 'Choose' %}
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item"
                                        href="{% url 'mail_job:change' seq=row.seq %}">{% trans 'Change' %}</a>
                                    <a class="dropdown-item"
                                        href="{% url 'mail_job:delete' seq=row.seq %}">{% trans 'Delete' %}</a>
                                    <a class="dropdown-item"
                                        href="{% url 'mail_job:mail_test' seq=row.seq %}">{% trans 'Mail test' %}</a>
                                </div>
                            </div>
                        </td>
                        <td class="advanced-field">{{ row.department }}</td>
                        <td>{{ row.event_class }}</td>
                        <td>{{ row.event }}</td>
                        <td>{{ row.mode_send_readable }}</td>
                        <td>{{ row.note_date|date:"Y-m-d" }}</td>
                        <td class="advanced-field">{{ row.stop_date|date:"Y-m-d" }}</td>
                        <td>{{ row.period_readable }}</td>
                        <td>{{ row.subject }}</td>
                        <td class"text-break">{{ row.body }}</td>
                        <td>{{ row.recipient_add }}</td>
                        <td>{{ row.recipient }}</td>
                        <td id="field-created-by-mail-job">{{ row.create_by }}</td>
                        <td>{{ row.start_date|date:"Y-m-d" }} {{ row.start_date|time:"H:i:s" }}</td>
                        <td class="advanced-field">{{ row.update_by }}</td>
                        <td class="advanced-field">{{ row.update_date|date:"Y-m-d" }}
                            {{ row.update_date|time:"H:i:s" }}</td>
                        <td class="advanced-field">{{ row.mail_count|floatformat:"0" }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row" style="height: 8rem"></div>
</div>
{% endblock %}

{% block extrajs %}
<script>
    var role = "{{ user }}";
</script>
<script type="text/javascript" src="{% static 'js/mail_job/change_list.js' %}"></script>
{% endblock %}

mail_job/templates/mail_job/delete.html
{% extends 'mail_job/base.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="container-fluid">
    <div class="row" style="height: 6rem;"></div>
    <div class="row justify-content-center">
        <div class="col-auto border-j3y-theme-2 rounded" style="padding: 1.5rem; width: 24rem;">
            <p><h1>{% trans 'Are you sure?' %}</h1></p>
            <br>
            <p><h6>{% trans 'Are you sure you want to delete this Mail Job?' %}</h6></p>
            <br>
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col">
                        <button type="submit" class="btn btn-danger btn-block">{% trans 'Delete' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-auto" style="padding: 1.5rem;">
        </div>
    </div>
</div>
{% endblock %}

mail_job/templates/mail_job/mail_test.html
{% extends 'mail_job/base.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="container-fluid">
    <div class="row" style="height: 6rem;"></div>
    <div class="row justify-content-center">
        <div class="col-auto border-j3y-theme-2 rounded" style="padding: 1.5rem; width: 24rem;">
            <p><h1>{% trans 'Are you sure?' %}</h1></p>
            <br>
            <p><h6>{% trans 'Are you sure you want to send the test mail of this Mail Job?' %}</h6></p>
            <br>
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col">
                        <button type="submit" class="btn btn-success btn-block">{% trans 'Send' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-auto" style="padding: 1.5rem;">
        </div>
    </div>
</div>
{% endblock %}