accounts/urls.py
from django.urls import path
from django.views.generic import RedirectView
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView)
from .views import sign_up, sign_up_with_account_password, sign_up_with_chief_email, profile_change, set_role
from .forms import EmailValidationOnForgotPassword


# we use many built-in auth-related views from django.contrib.auth.urls
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    # we override this form class of this view
    path('password-reset/', PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

# some custom views
urlpatterns += [
    path('sign-up/', sign_up, name='sign_up'),
    path('sign-up/with-account-password/', sign_up_with_account_password, name='sign_up_with_account_password'), # not shown directly on web interface
    path('sign-up/with-chief-email/', sign_up_with_chief_email, name='sign_up_with_chief_email'),
    path('profile/', profile_change, name='profile_change'),
    path('set-role/<str:role>/', set_role, name='set_role')
]

mail_job/urls.py
from django.urls import path
from .views import change_list, add, change, delete, mail_test


app_name = 'mail_job'

urlpatterns = [
    path('', change_list, name='change_list'),
    path('add/', add, name='add'),
    path('<int:seq>/change/', change, name='change'),
    path('<int:seq>/delete/', delete, name='delete'),
    path('<int:seq>/mail-test/', mail_test, name='mail_test'),
]

mssqlj3y/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('mail-job/', include('mail_job.urls')),
    path('', RedirectView.as_view(url='/mail-job/'), name='index'),
]

mssqlj3y/templates/base.html
{% load i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}
<!DOCTYPE html>
<html>

<head>

    {% block meta %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% endblock %}

    {% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@400;500;700;900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@400;500;700;900&display=swap"
        rel="stylesheet">
    {% endblock %}
    
    {% block extracss %}
    {% endblock %}

    {% block title %}
    <title>{% trans 'Reminder' %}</title>
    {% endblock title %}

</head>

<body>

    {% block nav %}
    {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-md navbar-light bg-j3y-theme-4" style="padding-left: 2rem; padding-right: 2rem;">
        <a class="navbar-brand pt-0" href="{% url 'index' %}">
            {% include 'brand_nav_icon.html' %}
            {% trans 'Reminder' %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#togglerTarget"
            aria-controls="togglerTarget" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon" style="padding-left: 2rem;"></span>
        </button>
        <div class="collapse navbar-collapse" id="togglerTarget">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        {% trans 'Mail Job' %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'mail_job:change_list' %}">{% trans 'View List' %}</a>
                        <a class="dropdown-item" href="{% url 'mail_job:add' %}">{% trans 'Add' %}</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item"
                            href="{% url 'mail_job:change_list' %}?show_history=true">{% trans 'History' %}</a>
                    </div>
                </li>
                <a class="nav-itrm nav-link" data-toggle="modal" href="#" data-target="#modalHelp">
                    {% trans 'Help' %}
                </a>
                {% include 'modal_help.html' %}
                <a class="nav-itrm nav-link" data-toggle="modal" href="#" data-target="#modalAbout">
                    {% trans 'About' %}
                </a>
                {% include 'modal_about.html' %}
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'logout' %}">{% trans 'Logout' %}</a>
                        <a class="dropdown-item" href="{% url 'profile_change' %}">{% trans 'Profile' %}</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">{% trans 'Password change' %}</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'sign_up' %}">{% trans 'Sign up' %}</a>
                        <a class="dropdown-item" href="{% url 'password_reset' %}">{% trans 'Password reset' %}</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        {% with default_role=request.user.profile.department.all.0.name %}
                        {{ request.session.role|default:default_role }}
                        {% endwith %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        {% for dep in user.profile.department.all %}
                        <a class="dropdown-item" href="{% url 'set_role' role=dep.name %}">{{ dep.name }}</a>
                        {% endfor %}
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        {{ LANGUAGE_CODE }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        {% for language in languages %}
                        <a class="dropdown-item set-language-item" href="#">{{ language.code }}</a>
                        {% endfor %}
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    {% else %}
    <nav class="navbar navbar-expand-md navbar-light bg-j3y-theme-4" style="padding-left: 2rem; padding-right: 2rem;">
        <a class="navbar-brand pt-0" href="{% url 'index' %}">
            {% include 'brand_nav_icon.html' %}
            {% trans 'Reminder' %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#togglerTarget"
            aria-controls="togglerTarget" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="togglerTarget">
            <ul class="navbar-nav mr-auto">
                <a class="nav-itrm nav-link" data-toggle="modal" href="#" data-target="#modalAbout">
                    {% trans 'About' %}
                </a>
                {% include 'modal_about.html' %}
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        {{ LANGUAGE_CODE }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        {% for language in languages %}
                        <a class="dropdown-item set-language-item" href="#">{{ language.code }}</a>
                        {% endfor %}
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    {% endif %}
    {% endblock %}

    {% block message %}
    {% if messages %}
    {% for message in messages %}
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <span class="navbar-text py-0 text-success">{{ message }}</span>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <span class="navbar-text py-0 text-danger">{{ message }}</span>
        {% else %}
        <span class="navbar-text py-0">{{ message }}</span>
        {% endif %}
    </nav>
    {% endfor %}
    {% endif %}
    {% endblock %}

    {% block tip %}
    {% if tips %}
    {% for tip in tips %}
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <span class="navbar-text py-0 text-secondary">{{ tip }}</span>
    </nav>
    {% endfor %}
    {% endif %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block basejs %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
    <script>
        $(document).ready(function () {
            $("a.set-language-item").on("click", function () {
                var csrfmiddlewaretoken = "{{ csrf_token }}"
                var url = "{% url 'set_language' %}"
                var language = $(this).text();
                $.ajax({
                    type: "POST",
                    url: url,
                    data: {
                        csrfmiddlewaretoken: csrfmiddlewaretoken,
                        language: language,
                    },
                    success: function () {
                        location.reload();
                    }
                });
            });
        });
    </script>
    {% endblock %}

    {% block extrajs %}
    {% endblock %}

</body>

</html>

mssqlj3y/templates/brand.html
{% load i18n %}
{% load static %}
<p>
    <a href="{% url 'index' %}">
        <svg class="bi bi-bell" width="8rem" height="8rem" viewBox="0 0 16 16" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2z" />
            <path fill-rule="evenodd"
                d="M8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z" />
        </svg>
    </a>
</p>

mssqlj3y/templates/brand_nav_icon.html
{% load i18n %}
{% load static %}
<svg class="bi bi-bell" width="1.5rem" height="1.5rem" viewBox="0 0 16 16" fill="currentColor"
    xmlns="http://www.w3.org/2000/svg">
    <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2z" />
    <path fill-rule="evenodd"
        d="M8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z" />
</svg>

mssqlj3y/templates/modal_about.html
{% load i18n %}
{% load static %}
<div class="modal fade" id="modalAbout" tabindex="-1" role="dialog" aria-labelledby="modalAboutLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="modalAboutLabel">{% trans 'About' %}</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="false">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>{% trans 'If there is a problem, please contact Jack Chang or Jimmy Lin.' %}</p>
            </div>
        </div>
    </div>
</div>

mssqlj3y/templates/modal_help.html
{% load i18n %}
{% load static %}
<div class="modal fade" id="modalHelp" tabindex="-1" role="dialog" aria-labelledby="modalHelpLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="modalHelpLabel">{% trans 'Help' %}</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="false">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>{% trans 'What does a mail job do?' %}</p>
                <p>{% trans 'It helps you remind yourself those you may miss, sending the specified email message according to your settings.' %}
                </p>
                <hr>
                <p>{% trans 'How can I get started?' %}</p>
                <p>
                    {% trans 'Use ' %}<a class="btn btn-secondary rounded mx-1" style="width: 6rem;"
                    href="{% url 'mail_job:add' %}">{% trans 'Add' %} +</a>
                    {% trans ' to create a new mail job for yourself.' %}</p>
                <p>{% trans 'After that, manage your Mail Job using Change, Delete and Mail Test function in the table showed below.' %}
                </p>
                <hr>
                <p>{% trans 'Here are some fields you may get confused about. You may check out these, if necessary:' %}
                </p>
                <table class="table j3y-table table-light bg-light table-striped">
                    <thead>
                        <tr style="text-align: left;">
                            <th>{% trans 'Field' %}</th>
                            <th>{% trans 'Description' %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>{% trans 'Dep.' %}</th>
                            <td>{% trans 'This mail job is for which department.' %}</td>
                        </tr>
                        <tr>
                            <th>{% trans 'Event type' %}</th>
                            <td>{% trans 'A plain text which simply classifies which event this is about.' %}</td>
                        </tr>
                        <tr>
                            <th>{% trans 'Event' %}</th>
                            <td>{% trans 'More detail about the event here.' %}</td>
                        </tr>
                        <tr>
                            <th>{% trans 'Start on' %}</th>
                            <td>{% trans 'The date on which mail job starts sending the notification by email.' %}</td>
                        </tr>
                        </tr>
                        <tr>
                            <th>{% trans 'Period' %}</th>
                            <td>{% trans 'After that, how frequently does mail job send the email.' %}</td>
                        </tr>
                        <tr>
                            <th>{% trans 'Mail subject' %}</th>
                            <td>{% trans 'The subject of email sent' %}</td>
                        </tr>
                        <tr>
                            <th>{% trans 'Mail content' %}</th>
                            <td>{% trans 'The content of email sent' %}</td>
                        </tr>
                        <tr>
                            <th>{% trans 'Recipients' %}</th>
                            <td>{% trans 'Those who would recieve the email.' %}</td>
                        </tr>
                        <tr>
                            <th>{% trans 'Created by' %}</th>
                            <td>{% trans 'Who created this mail job.' %}</td>
                        </tr>
                        <tr>
                            <th>{% trans 'Created date' %}</th>
                            <td>{% trans 'The date this mail job created.' %}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>